# adopted from https://gitlab.com/Ma27/nur-packages/raw/master/.gitlab-ci.yml

image: nixos/nix
stages: [build]

instantiation:
  stage: build
  script:
    # evaluation only, no artifacts -> no redistribution
    - export NIXPKGS_ALLOW_UNFREE=1 NIXPKGS_ALLOW_BROKEN=1
    - nix-instantiate -E 'with import <nixpkgs> { config.checkMeta = true; }; callPackage ./. { }'
    - nix-env -qa --json 'with import <nixpkgs> { config.checkMeta = true; }; callPackage ./. { }'
  artifacts:
    paths:
      - /nix/store/*.drv
